### PR TITLE
Neon support, perf improvements and fixes for warnings

### PR DESCRIPTION
**Pull request by stewartmiles**
Hi, a couple of us in Google have made a few modifications to vectorial.  We hope you're able to merge the following patch series:
* Support for SSE1/2
* Fix for gcc narrowing conversion warnings
* Return of determinant from simx4x4_inverse to detect matrices that can't be inverted
* Perf improvement for dot product, cross product and vec3 store
* 2f NEON implementation

Cheers,
Stewart

### CODE REVIEW

**Comment by stewartmiles** [comment]
Hi Mikko, it's been a few months any update on this?

**Comment by scoopr** [comment]
Whoops, sorry for the delay, newfound fatherhood has kept me preoccupied.
I've now merged the pr with the changes I've made earlier, as you didn't seem to have any comments on them, and I didn't remember any outstanding issues.

Thanks!

**Comment by stewartmiles** [comment]
Congratulations Mikko, I'm sure you'll continue to be very busy for many
years to come :)  Thanks for merging I'll let you know when we have moved
MathFu over to this or if anything comes up in the process.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
MathFu is moved over to upstream vectorial, see
https://github.com/google/mathfu/tree/master/dependencies and
https://github.com/google/mathfu/commit/2305cae374a921828cc048ce337769ce5844e213

Thanks,
Stewart

**Comment by scoopr** [comment]
Awesome!

**Pull request merged**
